<a href="https://colab.research.google.com/github/brian3245/CSC154_BRIANAGUIRRE/blob/main/CSC114%2C_Mod_2_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Assignment: Introduction to NumPy, Aggregations, and Universal Functions

# CSC-114

In these lab assignments, I will provide a file for you, as you can see here, and will have code cells present where I want you to insert your code. You can add / remove code cells as you see fit. Just be sure to answer the question(s) posed.

**Note: be sure to turn in notebook with code cells executed or it will be an automatic 0.**

## Task 1: Import Numpy and alias as np.

In [1]:
import numpy as np

## Task 2: Create & print a NumPy array of integers from 1 to 20.

In [3]:
x = np.arange(1, 21)
print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## Task 3: Perform & print basic arithmetic operations (+, -, *, /) on said array.

In [5]:
addition = x + 2
subtraction = x - 2
multiplication = x * 2
division = x / 2
print("Addition (+2): ", addition)
print("Subtraction (-2): ", subtraction)
print("Multiplication (*2): ", multiplication)
print("Division (/2): ", division)

Addition (+2):  [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
Subtraction (-2):  [-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Multiplication (*2):  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
Division (/2):  [ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


## Task 4: Calculate & print sum, mean, minimum, standard deviation, and maximum of said array.

In [7]:
sumx = np.sum(x)
meanx = np.mean(x)
minx = np.min(x)
stdx = np.std(x)
maxx = np.max(x)
print("Sum: ", sumx)
print("Mean: ", meanx)
print("Min: ", minx)
print("Standard Deviation: ", stdx)
print("Max: ", maxx)

Sum:  210
Mean:  10.5
Min:  1
Standard Deviation:  5.766281297335398
Max:  20


## Task 5: Use ufuncs to calculate the square root, square, and exponent of each element in said array.

In [8]:
sqrt_x = np.sqrt(x)
square_x = np.square(x)
exp_x = np.exp(x)
print("Square Root: ", sqrt_x)
print("Square: ", square_x)
print("Exponent: ", exp_x)

Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595]
Square:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]
Exponent:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08 4.85165195e+08]


## Task 6: Create a new NumPy array of random integers between 1 and 100 with a shape of 10x10. Calculate & print the sum of each column in this array.

In [9]:
y = np.random.randint(1, 101, size=(10, 10))
sum_y = np.sum(y, axis=0)
print("Sum of each column: ", sum_y)

Sum of each column:  [473 739 391 450 455 509 602 623 531 517]


## Task 7: find & print the transpose of the array.

In [14]:
transpose_y = np.transpose(y)
print("Transpose: \n", transpose_y)

Transpose: 
 [[ 53   7  80   5  58  41  61  69   2  97]
 [ 52  87  94  95   4  85  38  98  99  87]
 [ 75  95  27   7  27   6  87   6  29  32]
 [ 98  24  61  20  66  62  25   5  51  38]
 [ 55 100  56   6  63  31  52  42   8  42]
 [ 77  62  69  13  74  27  47  62  51  27]
 [  5  99  50  91  23  72  64  45  74  79]
 [ 90  71  68  20  35 100  68 100  65   6]
 [ 69  45  23  65  32  33  99  76  55  34]
 [ 76  52  54  37  50  80  46  12  99  11]]


## Task 8: Using the linalg module in NumPy, calculate and print the determinant of this matrix.

In [15]:
np.linalg.det(y)
print("Determinant: ", np.linalg.det(y))


Determinant:  3.5576219971632755e+17
